TRAIN:
  ENABLE: True
  DATASET: ssv2
  BATCH_SIZE: 64
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
  CHECKPOINT_FILE_PATH: <TRAIN-CHECKPOINT>
DATA:
  PATH_TO_DATA_DIR:: <SOMETHING-SOMETHING-V2-VIDEO>
  PATH_PREFIX: <SOMETHING-SOMETHING-V2-PATH-PREFIX>
  NUM_FRAMES: 32
  SAMPLING_RATE: 1
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
  TRAIN_JITTER_SCALES_RELATIVE: [0.9, 1.33]
  TRAIN_JITTER_ASPECT_RELATIVE: [1.0, 1.0]
  RANDOM_FLIP: False
AUG:
  ENABLE: True
  RE_PROB: 0.0
  AA_TYPE: rand-m20-n2-mstd0.5-inc1
SOLVER:
  BASE_LR: 0.01
  LR_POLICY: cosine
  WARMUP_EPOCHS: 2.5
  WARMUP_START_LR: 0.0
  COSINE_AFTER_WARMUP: True
  MAX_EPOCH: 35
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  OPTIMIZING_METHOD: sgd
MODEL:
  MODEL_NAME: ViViT
  NUM_CLASSES: 174
  ARCH : vivit
  LOSS_FUNC: cross_entropy
VIVIT:
  CONFIG_PATH: <VIVIT-CONFIG-PATH>
TEST:
  ENABLE: True
  DATASET: ssv2
  BATCH_SIZE: 16
  NUM_ENSEMBLE_VIEWS: 1
  NUM_SPATIAL_CROPS: 1
  CHECKPOINT_FILE_PATH: <TEST-CHECKPOINT>
DATA_LOADER:
  NUM_WORKERS: 4
  PIN_MEMORY: True
NUM_GPUS: 2
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .