TRAIN:
  ENABLE: True
  DATASET: epickitchens
  BATCH_SIZE: 128
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
  CHECKPOINT_FILE_PATH: <TRAIN-CHECKPOINT>
  CHECKPOINT_EPOCH_RESET: True
DATA:
  PATH_TO_DATA_DIR:
  NUM_FRAMES: 8
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
  INV_UNIFORM_SAMPLE: True
  RANDOM_FLIP: False
  REVERSE_INPUT_CHANNEL: False
AUG:
  ENABLE: True
  RE_PROB: 0.0
  AA_TYPE: rand-m15-n2-mstd0.5-inc1
EPICKITCHENS:
  VISUAL_DATA_DIR: <EPIC-KITCHENS-100-VIDEO>
  ANNOTATIONS_DIR: <EPIC-KITCHENS-100-ANNOTATIONS>
  TRAIN_LIST: EPIC_100_train.pkl
  VAL_LIST: EPIC_100_validation.pkl
  TEST_LIST: EPIC_100_validation.pkl
  TEST_SPLIT: validation
  TRAIN_PLUS_VAL: False
  NUM_CLASSES: [97, 300]
TIMESFORMER:
  ATTENTION_TYPE: 'divided_space_time'
SOLVER:
  BASE_LR: 0.005
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 11, 14]
  LRS: [1, 0.1, 0.01]
  MAX_EPOCH: 15
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  OPTIMIZING_METHOD: sgd
MODEL:
  MODEL_NAME: TimeSformer
  ARCH: timesformer
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True
  DATASET: epickitchens
  BATCH_SIZE: 128
  NUM_ENSEMBLE_VIEWS: 1
  NUM_SPATIAL_CROPS: 1
DATA_LOADER:
  NUM_WORKERS: 12
  PIN_MEMORY: True
NUM_GPUS: 4
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: <OUTPUT-DIR>