TRAIN:
  ENABLE: True
  DATASET: epickitchens
  BATCH_SIZE: 2
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
DATA:
  PATH_TO_DATA_DIR:
  NUM_FRAMES: 32
  SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
EPICKITCHENS:
  VISUAL_DATA_DIR: <EPIC-KITCHENS-100-VIDEO>
  ANNOTATIONS_DIR: <EPIC-KITCHENS-100-ANNOTATIONS>
  TRAIN_LIST: EPIC_100_train.pkl
  VAL_LIST: EPIC_100_validation.pkl
  TEST_LIST: EPIC_100_validation.pkl
  TEST_SPLIT: validation
  TRAIN_PLUS_VAL: False
  NUM_CLASSES: [97, 300]
  PARTICIPANT_FIRST: False
SOLVER:
  BASE_LR: 0.003125
  LR_POLICY: cosine
  WARMUP_EPOCHS: 2.5
  WARMUP_START_LR: 0.0
  COSINE_AFTER_WARMUP: True
  MAX_EPOCH: 15
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  OPTIMIZING_METHOD: sgd
MODEL:
  MODEL_NAME: ViViT
  ARCH : vivit
  LOSS_FUNC: cross_entropy
VIVIT:
  CONFIG_PATH: <VIVIT-CONFIG-PATH>
TEST:
  ENABLE: True
  DATASET: epickitchens
  BATCH_SIZE: 16
  NUM_ENSEMBLE_VIEWS: 1
  NUM_SPATIAL_CROPS: 1
  CHECKPOINT_FILE_PATH: <TEST-CHECKPOINT>
  NUM_WORKERS: 4
  PIN_MEMORY: True
NUM_GPUS: 2
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
