TRAIN:
  ENABLE: True
  DATASET: epickitchens
  BATCH_SIZE: 32
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
  CHECKPOINT_EPOCH_RESET: True
  MIXED_PRECISION: True
DATA:
  NUM_FRAMES: 16
  SAMPLING_RATE: 4
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
  MEAN: [0.5, 0.5, 0.5]
  STD: [0.5, 0.5, 0.5]
  PATH_TO_DATA_DIR:
EPICKITCHENS:
  VISUAL_DATA_DIR: <EPIC-KITCHENS-100-VIDEO>
  ANNOTATIONS_DIR: <EPIC-KITCHENS-100-ANNOTATIONS>
  TRAIN_LIST: EPIC_100_train.pkl
  VAL_LIST: EPIC_100_validation.pkl
  TEST_LIST: EPIC_100_validation.pkl
  TEST_SPLIT: validation
  TRAIN_PLUS_VAL: False
  NUM_CLASSES: [97, 300]
  PARTICIPANT_FIRST: False
SOLVER:
  BASE_LR: 1e-4
  LR_POLICY: steps_with_relative_lrs
  LRS: [1, 0.1, 0.01]
  STEPS: [0, 30, 40]
  MAX_EPOCH: 50
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-2
  WARMUP_EPOCHS: 0.0
  OPTIMIZING_METHOD: adamw
MIXUP:
  LABEL_SMOOTH_VALUE: 0.2
SLOWFAST:
  ALPHA: 8
MOTIONFORMER:
  PATCH_SIZE: 16
  PATCH_SIZE_TEMP: 2
  CHANNELS: 3
  EMBED_DIM: 768
  DEPTH: 12
  NUM_HEADS: 12
  MLP_RATIO: 4
  QKV_BIAS: True
  VIDEO_INPUT: True
  TEMPORAL_RESOLUTION: 8
  USE_MLP: True
  DROP: 0.0
  POS_DROPOUT: 0.0
  DROP_PATH: 0.0
  IM_PRETRAINED: True
  HEAD_DROPOUT: 0.0
  HEAD_ACT: tanh
  PRETRAINED_WEIGHTS: vit_1k
  ATTN_LAYER: trajectory
MODEL:
  ARCH: motionformer
  MODEL_NAME: Motionformer
  LOSS_FUNC: cross_entropy
TEST:
  ENABLE: True
  DATASET: epickitchens
  BATCH_SIZE: 32
  NUM_ENSEMBLE_VIEWS: 1
  NUM_SPATIAL_CROPS: 1
  CHECKPOINT_FILE_PATH: <TEST-CHECKPOINT>
DATA_LOADER:
  NUM_WORKERS: 4
  PIN_MEMORY: True
NUM_GPUS: 2
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .