TRAIN:
  ENABLE: True
  DATASET: ssv2
  BATCH_SIZE: 8
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
DATA:
  PATH_TO_DATA_DIR:: <SOMETHING-SOMETHING-V2-VIDEO>
  PATH_PREFIX: <SOMETHING-SOMETHING-V2-PATH-PREFIX>
  NUM_FRAMES: 16
  SAMPLING_RATE: 1
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.229, 0.224, 0.225]
SOLVER:
  BASE_LR: 0.005
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 11, 14]
  LRS: [1, 0.1, 0.01]
  MAX_EPOCH: 15
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  OPTIMIZING_METHOD: sgd
MODEL:
  MODEL_NAME: VideoMAE
  NUM_CLASSES: 174
  ARCH : videomae
  LOSS_FUNC: cross_entropy
VIDEOMAE:
    MODEL: 'vit_base_patch16_224'
    TUBELET_SIZE: 2
    FC_DROP_RATE: 0.0
    DROP_RATE: 0.0
    DROP_PATH_RATE: 0.0
    ATTN_DROP_RATE: 0.0
    USE_MEAN_POOLING: True
    INIT_SCALE: 0.001
TEST:
  ENABLE: True
  DATASET: ssv2
  BATCH_SIZE: 32
  NUM_ENSEMBLE_VIEWS: 1
  NUM_SPATIAL_CROPS: 1
  CHECKPOINT_FILE_PATH: <TEST-CHECKPOINT>
DATA_LOADER:
  NUM_WORKERS: 4
  PIN_MEMORY: True
NUM_GPUS: 2
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
