TRAIN:
  ENABLE: True
  DATASET: epickitchens
  BATCH_SIZE: 128
  EVAL_PERIOD: 5
  CHECKPOINT_PERIOD: 5
  AUTO_RESUME: True
  CHECKPOINT_FILE_PATH: <TRAIN-CHECKPOINT>
DATA:
  PATH_TO_DATA_DIR:
  NUM_FRAMES: 16
  SAMPLING_RATE: 2
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
  MEAN: [0.485, 0.456, 0.406]
  STD: [0.229, 0.224, 0.225]
  RANDOM_FLIP: False
AUG:
  ENABLE: True
  AA_TYPE: rand-m7-n4-mstd0.5-inc1
EPICKITCHENS:
  VISUAL_DATA_DIR: <EPIC-KITCHENS-100-VIDEO>
  ANNOTATIONS_DIR: <EPIC-KITCHENS-100-ANNOTATIONS>
  TRAIN_LIST: EPIC_100_train.pkl
  VAL_LIST: EPIC_100_validation.pkl
  TEST_LIST: EPIC_100_validation.pkl
  TEST_SPLIT: validation
  TRAIN_PLUS_VAL: False
  NUM_CLASSES: [97, 300]

SOLVER:
  BASE_LR: 0.001
  LR_POLICY: cosine
  WARMUP_START_LR: 0.0
  COSINE_END_LR: 2.0e-6
  WARMUP_EPOCHS: 5.0
  COSINE_AFTER_WARMUP: True
  MAX_EPOCH: 50
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-2
  OPTIMIZING_METHOD: adamw
  LAYER_DECAY: 0.75
MODEL:
  MODEL_NAME: VideoMAE
  ARCH : videomae
  LOSS_FUNC: cross_entropy
VIDEOMAE:
    MODEL: 'vit_base_patch16_224'
    TUBELET_SIZE: 2
    FC_DROP_RATE: 0.0
    DROP_RATE: 0.0
    DROP_PATH_RATE: 0.1
    ATTN_DROP_RATE: 0.0
    USE_MEAN_POOLING: True
    INIT_SCALE: 0.001
TEST:
  ENABLE: True
  DATASET: epickitchens
  BATCH_SIZE: 128
  NUM_ENSEMBLE_VIEWS: 1
  NUM_SPATIAL_CROPS: 1
DATA_LOADER:
  NUM_WORKERS: 12
  PIN_MEMORY: True
NUM_GPUS: 4
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: <OUTPUT-DIR>